name: Linux Release

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  ARTIFACT:     ${{ github.workspace }}/WaoStats.AppImage

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install compiler & Qt
      run: |
           sudo apt-get install --no-install-recommends make g++ qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5designer5 libqt5svg5-dev libfuse2 libxkbcommon-x11-0 appstream

    - name: Build DropboxQt
      working-directory: ${{ env.SOURCE_DIR }}/dropboxQt/prj
      run: |
           qmake -r dropboxQt.pro
           make -j8
           ls -al

    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/../build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/../build
      run: |
           qmake ${{ env.SOURCE_DIR }}/WaoStats.pro
           make -j8
           mkdir image
           cd image
           cp ${{ env.SOURCE_DIR }}/WaoStatsLogoMap.png .
           cp ${{ env.SOURCE_DIR }}/WaoStats.desktop .
           ls -al
           mkdir usr
           cd usr
           mkdir bin
           cd bin
           unzip ${{ env.SOURCE_DIR }}/adb/Linux/adb.zip
           chmod a+x adb
           ls -al

    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1.7.0
      with:
        plugins: qt appimage

    - name: Create Appimage
      working-directory: ${{ env.SOURCE_DIR }}/../build
      run: |
           # Install lib for linuxdeploy
           linuxdeploy-x86_64.AppImage --desktop-file=image/WaoStats.desktop --executable=WaoStats --appdir=image --plugin=qt --output=appimage --verbosity=3 --icon-file=image/WaoStatsLogoMap.png
           cp WaoStats-*.AppImage ${{ env.ARTIFACT }}
          
    - name: Save build artifact
      uses: actions/upload-artifact@master
      with:
        name: WaoStats
        path: ${{ env.ARTIFACT }}
